# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import os

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [2]:
#checking file path for my csv file.
os.getcwd()  #operating system fetch current working directory.

'/home/komen/Documents/moringa_school_projects/jet_airline_safety_project/dsc-course0-m8-lab'

In [3]:
os.listdir("data")  #listing what is inside.

['AviationData.csv', '.gitkeep', 'USState_Codes.csv']

In [4]:
#loading the file using an explicit ISO encoding shield to prevent special symbol crash.
df_raw = pd.read_csv("data/AviationData.csv", encoding="ISO-8859-1", low_memory=False)
#encoding matches characters(letters,symbols,puntuation)to specific numbers so that,
# computers can store and display them.
#encoding="ISO-8859-1" If we ignore this , python defaults to a dictionary called UTF-8, which
# doesn't know how to translate specific old hidden character code byte hence with throw "UnicodeDecodeError"
#low_memory=False forces pandas to look at all the thousands of rows to verify what datatype belongs
# to which column to avoid throwing DtypeWarning error.

In [5]:
df_raw.head(10) #inspect first ten rows.

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,42.445277,-70.758333,NaN,NaN,...,NaN,Air Canada,NaN,NaN,1.0,44.0,VMC,Climb,Probable Cause,19-09-2017
6,20001218X45446,Accident,CHI81LA106,1981-08-01,"COTTON, MN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,IMC,Unknown,Probable Cause,06-11-2001
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,Business,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
9,20020909X01560,Accident,MIA82DA029,1982-01-01,"JACKSONVILLE, FL",United States,NaN,NaN,JAX,JACKSONVILLE INTL,...,Personal,NaN,0.0,0.0,3.0,0.0,IMC,Cruise,Probable Cause,01-01-1982

In [6]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [7]:
df_raw.describe()   #summary statistics.

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

In [8]:
#Create data snapshot function to be re-used.
"""
    This function takes any dataframe and returns a ..
    summary of its types, missing values and top entry counts.
    """

def get_data_snapshot(any_dataframe):

    snapshot = pd.DataFrame({
        "Column Type": any_dataframe.dtypes,  #Extracts what data types lives in each column.
        "Missing Holes (NaN)": any_dataframe.isna().sum(),  # Counts NULL values missing in each column.
        "Missing Percentage (%)": (any_dataframe.isna().sum() / len(any_dataframe) * 100).round(2),   #Calculates missing values in percentage.
        # Finds What is the most common actual word/value?
        "Top Entry Value": [
            any_dataframe[col].value_counts().index[0] if any_dataframe[col].notna().any() else "Entirely Empty"
            for col in any_dataframe.columns  #We are getting only the first one and leaving the rest
            #index 0 gives the name of the champion on the left side only.
        ],
        "Top Value Count": [
            any_dataframe[col].value_counts().iloc[0] if any_dataframe[col].notna().any() else 0
            for col in any_dataframe.columns     #This iterates through columns and does necessary calculations.
        ] # This whole code tracks how frequent the top entry is.
        #Value counts show how many times a unique word appears in each column.(Highest to lowest)
    })
    return snapshot   #Returns dataframe snapshot.

get_data_snapshot(df_raw)

,Column Type,Missing Holes (NaN),Missing Percentage (%),Top Entry Value,Top Value Count
Event.Id,object,0,0.00,20001214X45071,3
Investigation.Type,object,0,0.00,Accident,85015
Accident.Number,object,0,0.00,WPR23LA045,2
Event.Date,object,0,0.00,1982-05-16,25
Location,object,52,0.06,"ANCHORAGE, AK",434
Country,object,226,0.25,United States,82248
Latitude,object,54507,61.32,332739N,19
Longitude,object,54516,61.33,0112457W,24
Airport.Code,object,38757,43.60,NONE,1488
Airport.Name,object,36185,40.71,Private,240
Injury.Severity,object,1000,1.12,Non-Fatal,67357
Aircraft.damage,object,3194,3.59,Substantial,64148
Aircraft.Category,object,56602,63.68,Airplane,27617
Registration.Number,object,1382,1.55,NONE,344
Make,object,63,0.07,Cessna,22227
Model,object,92,0.10,152,2367
Amateur.Built,object,102,0.11,No,80312
Number.of.Engines,float64,6084,6.84,1.0,69582
Engine.Type,object,7096,7.98,Reciprocating,69530
FAR.Description,object,56866,63.97,091,18221
Schedule,object,76307,85.85,NSCH,4474
Purpose.of.flight,object,6192,6.97,Personal,49448
Air.carrier,object,72241,81.27,Pilot,258
Total.Fatal.Injuries,float64,11401,12.83,0.0,59675
Total.Serious.Injuries,float64,12510,14.07,0.0,63289
Total.Minor.Injuries,float64,11933,13.42,0.0,61454
Total.Uninjured,float64,5912,6.65,0.0,29879
Weather.Condition,object,4492,5.05,VMC,77303
Broad.phase.of.flight,object,27165,30.56,Landing,15428
Report.Status,object,6384,7.18,Probable Cause,61754
Publication.Date,object,13771,15.49,25-09-2020,17019

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized